Add `finished` support
holepunchto/bare-stream pull request #2
Opened 2024-08-20 19:25 UTC by yassernasc

Ref: https://nodejs.org/api/stream.html#streamfinishedstream-options

The implementation was focused on the minimum required to make the tests pass, all of them with node.js compatibility.

2024-08-21 07:06 UTC, kasperisager requested changes

2024-08-21 07:06 UTC, kasperisager commented on index.js
> +  }
```suggestion
  if (typeof opts === 'function') {
    cb = opts
    opts = {}
  }

  if (!opts) opts = {}
  
  const {
    error = true,
    readable = stream.readable,
    writable = stream.writable,
    cleanup = false
  } = opts
```

This is a general pattern in JavaScript when dealing with overloaded functions:

1. First, shuffle `cb` into place, zeroing the overloaded arguments along the way.
2. Then, zero any possibly nullish arguments.
3. Finally, destructure the `opts` argument with appropriate defaults.

This change will cause issues with the following code, I'll tweak bits as necessary.

2024-08-21 07:06 UTC, kasperisager commented on package.json
> +    "bare-http1": "^3.8.0",
This creates a cycle between `bare-stream` and `bare-http1` so let's not test against that. You want to test streams in isolation anyway, so mock out `Readable`/`Writable` streams as appropriate.

2024-08-21 07:22 UTC, kasperisager requested changes

2024-08-21 07:22 UTC, kasperisager commented on test.js
> +  })
Brittle doesn't handle subtests terrible well, not supporting things like `.solo` for example. Let's make each test a top-level test case.

2024-08-21 07:28 UTC, kasperisager commented on test.js
> +  })
This is getting fixed in Brittle 👏

2024-08-21 17:29 UTC, yassernasc commented on index.js
> +  }
thanks for documenting here the steps

2024-08-21 17:30 UTC, yassernasc commented on index.js
> +    cb(stream.getStreamError(_stream, { all: true }))
the `{ all: true }` is related with: https://github.com/mafintosh/streamx/pull/91

2024-08-22 11:34 UTC, kasperisager approved these changes
Fantastic! 👏

2024-08-26 12:09 UTC, merged